### ISSUE TITLE
Rubocop 0.37.2

### ISSUE THREAD

**Issue by nijikon** [polishgeeks/polishgeeks-dev-tools#44]
In order for us to upgrade to rubocop 0.37.1, this things need to happen

- [x] reek ruby 2.3 support troessner/reek#801, troessner/reek#827
- [x] rubycritic need to bump its dependency to newest reek, whitesmith/rubycritic#105
- [x] rubocop-rspec rubocop 0.37.1 support nevir/rubocop-rspec#60, nevir/rubocop-rspec#62,

**Comment by chastell** [comment]
Just to let you know: using RuboCop 0.36 along Reek is blocked because RuboCop (rightly so) depends on `parser >= 2.3.0.1` while Reek depends on unparser which depends on `parser ~> 2.2.2`. Bumping unparser’s dependency probably won’t happen soon, so we’re working on dropping unparser, but it will take us a bit. Sorry!

**Comment by nijikon** [comment]
@chastell Yes I did noticed that, I will monitor the other issue, thanks!

**Comment by chastell** [comment]
We’ve released Reek 3.9.0, which at least bumps the Parser dependency so you can use Reek and newest RuboCop together. :)

**Comment by nijikon** [comment]
Yup, I noticed that thanks! Waiting for rubycritic to bump it to reek 3.9.0 :)
